[package]
name = "anagram"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
eyre = "0.6.5"
itertools = "0.10.1"
tokio = "1.10.0"
